/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteDialog.java
 *
 * Created on 07-11-2010, 05:13:07 PM
 */

package mgames;

/**
 *
 * @author Daniel
 */
public class ClienteDialog extends javax.swing.JDialog {

    /** Creates new form ClienteDialog */
    public ClienteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexoGroup = new javax.swing.ButtonGroup();
        codigoClienteLabel = new javax.swing.JLabel();
        paternoClienteLabel = new javax.swing.JLabel();
        nombreClienteLabel = new javax.swing.JLabel();
        maternoClienteLabel = new javax.swing.JLabel();
        codigoClienteField = new javax.swing.JTextField();
        nombreClienteField = new javax.swing.JTextField();
        paternoClienteField = new javax.swing.JTextField();
        maternoClienteField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        masculinoRadio = new javax.swing.JRadioButton();
        femeninoRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mgames.MGamesApp.class).getContext().getResourceMap(ClienteDialog.class);
        codigoClienteLabel.setText(resourceMap.getString("codigoClienteLabel.text")); // NOI18N
        codigoClienteLabel.setName("codigoClienteLabel"); // NOI18N

        paternoClienteLabel.setText(resourceMap.getString("paternoClienteLabel.text")); // NOI18N
        paternoClienteLabel.setName("paternoClienteLabel"); // NOI18N

        nombreClienteLabel.setText(resourceMap.getString("nombreClienteLabel.text")); // NOI18N
        nombreClienteLabel.setName("nombreClienteLabel"); // NOI18N

        maternoClienteLabel.setText(resourceMap.getString("maternoClienteLabel.text")); // NOI18N
        maternoClienteLabel.setName("maternoClienteLabel"); // NOI18N

        codigoClienteField.setText(resourceMap.getString("codigoClienteField.text")); // NOI18N
        codigoClienteField.setName("codigoClienteField"); // NOI18N

        nombreClienteField.setText(resourceMap.getString("nombreClienteField.text")); // NOI18N
        nombreClienteField.setName("nombreClienteField"); // NOI18N

        paternoClienteField.setText(resourceMap.getString("paternoClienteField.text")); // NOI18N
        paternoClienteField.setName("paternoClienteField"); // NOI18N

        maternoClienteField.setText(resourceMap.getString("maternoClienteField.text")); // NOI18N
        maternoClienteField.setName("maternoClienteField"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        sexoGroup.add(masculinoRadio);
        masculinoRadio.setSelected(true);
        masculinoRadio.setText(resourceMap.getString("masculinoRadio.text")); // NOI18N
        masculinoRadio.setName("masculinoRadio"); // NOI18N

        sexoGroup.add(femeninoRadio);
        femeninoRadio.setText(resourceMap.getString("femeninoRadio.text")); // NOI18N
        femeninoRadio.setName("femeninoRadio"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paternoClienteLabel)
                    .addComponent(maternoClienteLabel)
                    .addComponent(nombreClienteLabel)
                    .addComponent(codigoClienteLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(maternoClienteField)
                        .addComponent(paternoClienteField)
                        .addComponent(nombreClienteField)
                        .addComponent(codigoClienteField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(masculinoRadio)
                    .addComponent(femeninoRadio))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoClienteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoClienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreClienteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreClienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paternoClienteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paternoClienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maternoClienteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maternoClienteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masculinoRadio)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(femeninoRadio)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClienteDialog dialog = new ClienteDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoClienteField;
    private javax.swing.JLabel codigoClienteLabel;
    private javax.swing.JRadioButton femeninoRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton masculinoRadio;
    private javax.swing.JTextField maternoClienteField;
    private javax.swing.JLabel maternoClienteLabel;
    private javax.swing.JTextField nombreClienteField;
    private javax.swing.JLabel nombreClienteLabel;
    private javax.swing.JTextField paternoClienteField;
    private javax.swing.JLabel paternoClienteLabel;
    private javax.swing.ButtonGroup sexoGroup;
    // End of variables declaration//GEN-END:variables

}
